root: true
env:
    node: true
    browser: true
extends:
    - brainbits-typescript
parserOptions:
    project: ./tsconfig.json
rules:
    class-methods-use-this: [off]
    no-underscore-dangle: [off]
    arrow-parens: [off]
overrides:
  - files: ["*.js"]
    rules:
        '@typescript-eslint/explicit-function-return-type': [off]
        '@typescript-eslint/restrict-template-expressions': [off]
