import { vi } from 'vitest';
import KankaApi from '../KankaApi';

export default vi.fn<[], Omit<KankaApi, 'limiter'>>(() => ({
    isReady: true,
    reset: vi.fn(),
    switchUser: vi.fn(),
    getToken: vi.fn(),
    switchBaseUrl: vi.fn(),
    getAllCampaigns: vi.fn(),
    getCampaign: vi.fn(),
    getCharacter: vi.fn(),
    getAllCharacters: vi.fn(),
    getCreature: vi.fn(),
    getAllCreatures: vi.fn(),
    getAbility: vi.fn(),
    getAllAbilities: vi.fn(),
    getFamily: vi.fn(),
    getAllFamilies: vi.fn(),
    getItem: vi.fn(),
    getAllItems: vi.fn(),
    getJournal: vi.fn(),
    getAllJournals: vi.fn(),
    getLocation: vi.fn(),
    getAllLocations: vi.fn(),
    getNote: vi.fn(),
    getAllNotes: vi.fn(),
    getOrganisation: vi.fn(),
    getAllOrganisations: vi.fn(),
    getQuest: vi.fn(),
    getAllQuests: vi.fn(),
    getRace: vi.fn(),
    getAllRaces: vi.fn(),
    getEvent: vi.fn(),
    getAllEvents: vi.fn(),
    getEntity: vi.fn(),
    getAllEntities: vi.fn(),
    baseUrl: 'https://api.kanka.io/1.0',
}));
